hero:
  title: Product Owner
  text: Having a clear product vision from the product owner helps motivate and inspire the product team to the right direction.
  image:
    filename: pb-playerpo@2x.png
    alt: ...
description: The product owner role represents the interests of the customer for the development team. As the customer stakeholder, you are responsible for defining the outcomes of a product and ensuring there is always a user advocate involved in the product development cycle.
responsibilities:
  - title: Set a product vision and scope
    text: The product vision represents the core essence of the project. The vision is what the customer wish to build based on the problem they wish to solve. Once a problem is identified, the product team develops a strategy and plan to solve it.
  - title: Set project priorities
    text: Set priorities based on feedback from users and business value metrics to drive the development team’s strategy and the direction of the project.
  - title: Identify pain points
    text: As the voice of the customer, communicate to the product team the pain points of the current process. This practice gives the product team direction in how to design features that will mitigate user pain.
  - title: Track measurable objectives
    text: Measurable objectives can help you gauge the progress of the product team. You can change or prioritize metrics based on the work being done on the product. Decide when these objectives are met and when the product is ready for use.
  - title: Remove blockers to get to users
    text: Act as the point of contact between the product team and users of the application. Make yourself available to the team during the product development process. This is necessary to facilitate communication and identify problems with the product.
  - title: Trust the product team
    text: Trust the product team to create solutions to the problems you wish to solve. Once you establish a strategic direction for the product team, let them build the solution.
